### ISSUE TITLE
mapController.moveCamera should not be animated

### ISSUE THREAD

**Issue by ateich** [LuisThein/apple_maps_flutter#31]
**Describe the bug**
`mapController.moveCamera` should move the map without animating the transition to match the API of `google_maps_flutter`.

If an animated transition is required, `mapController.animateCamera` should be used instead.

---

From the GoogleMap API documentation:

[GoogleMap API - moveCamera](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#moveCamera(com.google.android.gms.maps.CameraUpdate))
`public final void moveCamera (CameraUpdate update)`

> Repositions the camera according to the instructions defined in the update. The move is instantaneous, and a subsequent getCameraPosition() will reflect the new position. See CameraUpdateFactory for a set of updates.

[GoogleMap API - animateCamera](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#animateCamera(com.google.android.gms.maps.CameraUpdate))
`public final void animateCamera (CameraUpdate update)`

> Animates the movement of the camera from the current position to the position defined in the update. During the animation, a call to getCameraPosition() returns an intermediate location of the camera.

---

**To Reproduce**
1. In the example project, open Camera control
2. Tap on any of the buttons
3. Observe the map camera animating to the new position

**Expected behavior**
The map should instantly transition to the new position, rather than animating the transition.

**Screenshots**
Not applicable.

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - Version iOS 15.0.2

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
    ! Error: iPhone is busy: Making the device ready for development. Xcode will continue when iPhone is finished. (code -10)

• No issues found!
```

**Root Cause**
Lines 232 and 235 of `apple_maps_flutter/ios/Classes/MapView/AppleMapController.swift` show `animated: true`

https://github.com/LuisThein/apple_maps_flutter/blob/d302d013d38315ac0e2b9742220df1fe6eeb17bf/ios/Classes/MapView/AppleMapController.swift#L228-L237

**Concerns**
While fixing this bug will make the API match what is expected from the Google Maps API (and `google_maps_flutter`), it is a breaking change for any users that have come to expect  `mapController.moveCamera` to animate.

While users can update their code to use `mapController.animateCamera` if they want the camera to animate, it should be very clear to anyone updating that this update will change existing behavior.

**Pull Request**
I'll submit a pull request changing `mapController.moveCamera` to no longer animate, if this sounds good to you. 

Given that this change breaks previous behavior, do you think it would warrant a major version bump?

**Comment by terry8204** [comment]
please help merge it.
