### ISSUE TITLE
Presence of android/ directory breaks Android builds on Flutter 2.10

### ISSUE THREAD

**Issue by stuartmorgan** [LuisThein/apple_maps_flutter#33]
**Describe the bug**
See https://github.com/flutter/flutter/issues/97729

**To Reproduce**
1. Make a new Flutter application project with 2.10
2. Add `apple_maps_flutter` to it
3. Try to build the app for Android

**Expected behavior**
Successful build.

While this is a bug in Flutter, and will be fixed there, you can fix this in the plugin simply by removing the unused `android/` folder; see https://github.com/flutter/flutter/issues/97729#issuecomment-1030139198.

You should set its minimum Flutter version to 1.17 as part of that change.

**Comment by LuisThein** [comment]
Hey, thank you for letting me know!
I updated the package and removed the unused `android` folder.
