### ISSUE TITLE
Don't request permission if the user location isn't required.

### ISSUE THREAD

**Issue by JoeCiou** [LuisThein/apple_maps_flutter#6]
Hello author, thank you for your great package.
I use the package on my app for display map without user location. but for now, the package also needs to request location permission to users. could you fix it?

**Comment by LuisThein** [comment]
Hey, thanks for reporting!
Thanks for pointing that out, It should already be fixed in version 0.0.6+3.

**Comment by Trulsmatias** [comment]
Maybe this fix should be reflected in the readme? I had to check if there was an issue regarding this to know it was not necessary after all.
